@startuml

usecase Sequence[
    Sequence
    
    ---
    FirstTimeDetectPlayer
]
card CheckBoolean[
    CheckBoolean
    ---
    isOnSpawnPosition
]
card CheckDetection[
    CheckDetection
    ---
    Detect Player
]
card Stop
card Wait
card PlayAnimation[
    PlayAnimation
    ---
    Standup Animation
]
card SetBoolean[
    isOnSpawnPosition=false
]
Sequence-->CheckBoolean
Sequence-->CheckDetection
Sequence-->Stop
Sequence-->Wait
Sequence-->PlayAnimation
Sequence-->SetBoolean

@enduml