@startuml

usecase Sequence[
    Sequence

    ---
    ReturnSpawnPosition
]
hexagon Inverter
card CheckBoolean[
    CheckBoolean
    ---
    isOnSpawnPosition
]
card PlayAnimaton0[
    PlayAnimaton0
    ---
    Walk Animation
]
card PlayAudio[
    Audio Walk
]
card ReturnToPosition
card PlayAnimation1[
    PlayAnimation1
    ---
    Sitted Animation
]
card SetBoolean[
    isOnSpawnPosition = false
]


Sequence-->Inverter
Inverter-->CheckBoolean
Sequence-->PlayAnimaton0
Sequence-->PlayAudio
Sequence-->ReturnToPosition
Sequence-->PlayAnimation1
Sequence-->SetBoolean



@enduml