@startuml

usecase Sequence[
    Sequence
    
    ---
    Monster Run To Player
]
card CheckSkillUseable
card PlayAnimation0[
    PlayAnimation
    ---
    Run Animation
]
card PlayAudio[
    PlayAudio
    ---
    Audio Run
]
card RunToPlayer
card PlayAnimation1[
    PlayAnimation
    ---
    Idle Animation
]

Sequence-->CheckSkillUseable
Sequence-->PlayAnimation0
Sequence-->PlayAudio
Sequence-->RunToPlayer
Sequence-->PlayAnimation1

@enduml