@startuml

usecase Sequence[
    Sequence
    
    ---
    MonsterDamaged
]
card CheckBoolean[
    CheckBoolean
    ---
    isDamaged
]
card StopParticle
card PlayAnimation[
    PlayAnimation
    ---
    Damaged Animation
]
card Wait
card ChasePlayer
card SetBoolean[
    SetBoolean
    ---
    isDamaged=false
]

Sequence-->CheckBoolean
Sequence-->StopParticle
Sequence-->PlayAnimation
Sequence-->Wait
Sequence-->ChasePlayer
Sequence-->SetBoolean

@enduml