@startuml

usecase Sequence[
    Sequence
    
    ---
    MonsterDead
]
card CheckBoolean[
    CheckBoolean
    ---
    isMonsterDead
]
card Stop
card PlayAnimation[
    PlayAnimation
    ---
    Death Animation
]
card SetBoolean[
    SetBoolean
    ---
    isMonsterDead=false
]

Sequence-->CheckBoolean
Sequence-->Stop
Sequence-->PlayAnimation
Sequence-->SetBoolean

@enduml