@startuml

[*]-->Sequencer
Sequencer-->CheckDetection
Sequencer : ChasePlayer
CheckDetection : Detect Chase Player
Sequencer-->PlayAnimation
PlayAnimation : Walk Animation
Sequencer-->PlayAudio
Sequencer-->SetAgentToPlayer

@enduml