@startuml

usecase Sequence[
    Sequence

    ---
    Chase Player
]
card CheckDetection[
    CheckDetection
    ---
    Chase Player Detection
]
card PlayAnimation[
    PlayAnimation
    ---
    Walk Animation
]
card PlayAudio[
    PlayAudio
    ---
    Audio Walk
]
card SetMoveTarget[
    SetMoveTarget
    ---
    Target : Player
]

Sequence-->CheckDetection
Sequence-->PlayAnimation
Sequence-->PlayAudio
Sequence-->SetMoveTarget

@enduml