@startuml

usecase Sequence[
    Sequence

    ---
    NearPlayer
]
card CheckPlayerIsNear[
    CheckPlayerIsNear
    ---
    PlayerDistance>StoppingDistance
]
card PlayAudio[
    PlayAudio
    ---
    Audio AtatckIdle
]
card LookPlayer
card PlayAnimation[
    PlayAnimation
    ---
    AttackIdle Animation
]

Sequence-->CheckPlayerIsNear
Sequence-->PlayAudio
Sequence-->LookPlayer
Sequence-->PlayAnimation

@enduml