@startuml

[*]-->Sequencer
Sequencer-->CheckBoolean
Sequencer : Overtravel
Sequencer-->PlayAnimation0
PlayAnimation0 : Walk Animation
Sequencer-->PlayAudio
Sequencer-->ReturnToPoisition
Sequencer-->PlayAnimation1
PlayAnimation1 : Sitted Animation

@enduml