@startuml

usecase Sequencer[
    Sequencer
    
    ---
    Overtravel
]
card CheckBoolean[
    CheckBoolean
    ---
    isOvertraveled
]
card PlayAnimation0[
    PlayAnimation0
    ---
    Walk Animation
]
card PlayAudio[
    PlayAudio
    ---
    Walk Audio
]
card ReturnToPoisition
card PlayAnimation1[
    PlayAnimation1
    ---
    SittedAnimation
]

Sequencer-->CheckBoolean
Sequencer-->PlayAnimation0
Sequencer-->PlayAudio
Sequencer-->ReturnToPoisition
Sequencer-->PlayAnimation1


@enduml