@startuml

usecase Sequence[
    Sequence

    ---
    Patrol
]
card CheckPlayerDetection
card PlayAnimation0[
    PlayAnimation
    ---
    Walk Animation
]
card PlayAudio0[
    PlayAudio
    ---
    Audio Walk
]
card PatrolToPoint
card PlayAnimation1[
    PlayAnimation
    ---
    Idle Animation
]
card PlayAudio1[
    PlayAudio
    ---
    Audio Idle
]
card Wait



Sequence-->CheckPlayerDetection
Sequence-->PlayAnimation0
Sequence-->PlayAudio0
Sequence-->PatrolToPoint
Sequence-->PlayAnimation1
Sequence-->PlayAudio1
Sequence-->Wait


@enduml